packages:
  - packages/*

catalog:
  "@antfu/eslint-config": ^4.13.1
  "@ayingott/prettier-config": ^2.1.4
  "@ayingott/sucrose": ^0.0.37
  "@types/eslint-plugin-tailwindcss": ^3.17.0
  "@types/node": ^22.15.19
  bumpp: ^10.1.1
  eslint: ^9.27.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-prettier: ^5.4.0
  eslint-plugin-tailwindcss: ^3.18.0
  lint-staged: ^16.0.0
  local-pkg: ^1.1.1
  prettier: ^3.5.3
  simple-git-hooks: ^2.13.0
  taze: ^19.1.0
  tsdown: ^0.11.11
  typescript: ^5.8.3

onlyBuiltDependencies:
  - rolldown
  - simple-git-hooks
  - unrs-resolver
